geoserver:
 image: kartoza/geoserver 
 ports:
  - "8080:8080"
 #networks:
 # - default 
 links:
  - "db"
 #depends_on:

db:
 build: postgis/.
 #image: ppensier/postgis
 #ports:
 # - "5432:5432"
 #networks:
 # - default
