geoserver:
 image: kartoza/geoserver 
 ports:
  - "8080:8080"
 #networks:
 # - default 
 links:
  - "db"
 #depends_on:

db:
 build: postgis/.
 #image: ppensier/postgis
 #ports:
 # - "5432:5432"
 #networks:
 # - default
pgpool:
 image:zakaria0086/pgpool
 ports:
  - "15432:5432"
 networks:
  - default
  
haproxy:
 image: zakaria086/haproxy
 ports:
  -  "80:80"
  -  "8888:8080"
 networks:
  - default
